### ISSUE TITLE
No connection on local device.

### ISSUE THREAD

**Issue by Mathmaclar** [josephdadams/TallyArbiter-GPOListener#2]
hey, thanks for the awesome tally server just having an issue with the GPO Listener.

I am running the GPO listener on the same raspberry pi 4 I'm running the Tally Arbiter server on. I am not currently able to get the two to connect. The terminal says it has connected when running the .py file (it says that for every IP, even dead ones) but no listener appears in the server. 

I've tried the IP and hostname in the config file and nothing seems to be coming up. Is this due to them being on the same machine? 

I have also tried running the GPOListener on a PiZero separately to the server to no avail either.

Any help on this matter would be great.

**Comment by Mathmaclar** [comment]
solved, used the blink(1) .py file instead and changed all the blink library stuff to use the gpiozero library instead and set it to 127.0.0.1 4455. works a treat, and with multiple instances running at startup. Thanks again, this is a great project!

**Comment by sukovec** [comment]
This seems like some problem with python socket.io library. Today I'm trying to use this and I'm getting `Unable to connect to Tally Arbiter server: 127.0.0.1 4455` error message, but in Wireshark I can see that it connects successfully (HTTP 200) to `http://127.0.0.1:4455/socket.io/?transport=polling&EIO=4&t=1607777162.4440136`, then Arbiter responds with `96:0{"sid":"WYvgVeaffIQXC2oCAACe","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}2:40` and then GPOListener (socketio) disconnects.

Not sure the reason for this, going to dig deeper.
