### ISSUE TITLE
GPOListener causes TallyArbiter exception

### ISSUE THREAD

**Issue by scoobiekw** [josephdadams/TallyArbiter-GPOListener#3]
RaspPi 4, 4Gb. Both GPOListener and TallyArbiter are on the same machine.

Tally Arbiter working as expected. M5Stick and Web working correctly.

When GPOListener connects to TallyArbiter it logs this error.

This is likely the same problem I've encountered in RelayListener

0|TallyArbiter  | [Tue Oct 06 2020 15:14:34 GMT-0500 (CDT)]     Caught exception: TypeError: Cannot read property 'id' of undefined
0|TallyArbiter  | TypeError: Cannot read property 'id' of undefined
0|TallyArbiter  |     at Socket.<anonymous> (/home/pi/tallyarbiter/index.js:546:41)
0|TallyArbiter  |     at emitOne (events.js:116:13)
0|TallyArbiter  |     at Socket.emit (events.js:211:7)
0|TallyArbiter  |     at /home/pi/tallyarbiter/node_modules/socket.io/lib/socket.js:528:12
0|TallyArbiter  |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
0|TallyArbiter  |     at Immediate._tickCallback [as _onImmediate] (internal/process/next_tick.js:181:9)
0|TallyArbiter  |     at runCallback (timers.js:810:20)
0|TallyArbiter  |     at tryOnImmediate (timers.js:768:5)
0|TallyArbiter  |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|TallyArbiter  | [Tue Oct 06 2020 15:14:34 GMT-0500 (CDT)]     Caught exception: TypeError: Cannot read property 'id' of undefined

**Comment by josephdadams** [comment]
This should be fixed in the latest. Let me know if that's not the case.
