### ISSUE TITLE
GPO Listener unable to connect to server

### ISSUE THREAD

**Issue by evenover** [josephdadams/TallyArbiter-GPOListener#4]
Hi!
I'm quite new to code so it's probably just a minor issue with my setup. I've tried both localhost and running the server on another computer and i still get the same error.

I'm getting the error:

 Unable to connect to Tally Arbiter server: 127.0.0.1 4455
Traceback (most recent call last):
  File "tallyarbiter-gpolistener.py", line 165, in <module>
^C    sio.connect('http://' + server_config['ip'] + ':' + str(server_config['port']))
  File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 284, in     connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection refused by the server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tallyarbiter-gpolistener.py", line 173, in <module>
    time.sleep(15)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 39, in     signal_handler
    return original_signal_handler(sig, frame)
  File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 26, in     signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt

**Comment by Nominari** [comment]
Had the same issue - this is likely caused by incompatibility of the latest socket.io client to the socket.io server version. 
Just uninstall the client with 
`sudo pip3 uninstall python-socketio[client]`

and install the last version 4 client with
`sudo pip3 install python-socketio==4.6.1`

… tadaaa - it connects right away ;-)

**Comment by evenover** [comment]
Ah, that's it! I was only downgrading the server socket.io and not the client.

Thanks!

**Comment by ruebyi** [comment]
hi, I'm running into the same problem, but I'm not able to install socketio via pip3.
There is a Client Error.
Any other way to do this?
