### ISSUE TITLE
Unable to install - no Such file or directory

### ISSUE THREAD

**Issue by ruebyi** [josephdadams/TallyArbiter-GPOListener#5]
Hi,
I'm trying to install GPOListener on a Pi Zero with the latest piOS.

My problem is, that the following command is not working:
https://raw.githubusercontent.com/josephdadams/TallyArbiter-GPOListener/master/tallyarbiter-gpolistener.py

I get "No such file or directory"

Is there a problem in the readme or in the direcotry?

Best Tobias

**Comment by josephdadams** [comment]
Did you run the `wget` command with this URL?
