### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by torstenwild** [josephdadams/TallyArbiter-GPOListener#6]
Deat All,
newbie, pls ask for help.

Server running and working in standard 127.0.0.1 4455
Installation on Pi Zero succesful
ssh access in wlan works
after start continious messages unable to connect to server 127.0.0.1 4455
Any idea?

**Comment by josephdadams** [comment]
127.0.0.1 is the localhost address and not accessible by other computers, you need to use your LAN ip of the server when accessing it from the Pi

https://en.wikipedia.org/wiki/Localhost
